import { Team } from '../types/team';

export const predefinedTeams: Team[] = [
  {
    name: 'Royals',
    logo: 'royals.png',
    themeColor: '#ffd147ff',
    players: [
      {
        name: 'Josh Brown',
        role: 'AR',
        orderType: 'TOP',
        isCaptain: false,
        batting: 75,
        bowling: 40,
        bowlingType: 'Right arm Medium',
      },
      {
        name: 'Binod Bhandari',
        role: 'WK',
        orderType: 'TOP',
        isCaptain: false,
        batting: 65,
        bowling: 0,
      },
      {
        name: 'Chris Lynn',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 82,
        bowling: 30,
      },
      {
        name: 'Aarif Sheikh',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 68,
        bowling: 50,
      },
      {
        name: 'Ishan Pandey',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 60,
        bowling: 15,
      },
      {
        name: 'Dipendra Singh Airee',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: true,
        batting: 80,
        bowling: 65,
        bowlingType: 'Right arm Medium',
      },
      {
        name: 'Harmeet Singh',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 68,
        bowling: 67,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Scott Kuggeleijn',
        role: 'BAT',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 55,
        bowling: 70,
      },
      {
        name: 'Hemant Dhami',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 60,
        bowling: 60,
        bowlingType: 'Right arm Medium',
      },
      {
        name: 'Naren Saud',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 35,
        bowling: 55,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Abinash Bohara',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 40,
        bowling: 65,
        bowlingType: 'Right arm Medium',
      },
      {
        name: 'Dipak Bohara',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 55,
        bowling: 45,
      },
      {
        name: 'Tek Rawat',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 52,
        bowling: 40,
      },
      {
        name: 'Dipendra Thapa',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 50,
        bowling: 42,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Milan Bohara',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 58,
        bowling: 20,
      },
    ],
  },
  {
    name: 'Gurkhas',
    logo: 'gurkhas.png',
    themeColor: '#762485ff',
    players: [
      {
        name: 'Aakash Tripathi',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 67,
        bowling: 30,
      },
      {
        name: 'Ben Charlesworth',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 74,
        bowling: 30,
      },
      {
        name: 'Bhim Sharki',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 82,
        bowling: 40,
      },
      {
        name: 'Milind Kumar',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 59,
        bowling: 43,
        bowlingType: 'Right arm Offbreak',
      },
      {
        name: 'John Simpson',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 58,
        bowling: 0,
      },
      {
        name: 'Gerhard Erasmus',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 75,
        bowling: 65,
        bowlingType: 'Right arm Offbreak',
      },
      {
        name: 'Mohammad Aadil Alam',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 70,
        bowling: 65,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Rashid Khan',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 41,
        bowling: 63,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Karan KC',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: true,
        batting: 69,
        bowling: 80,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Shahab Alam',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 55,
        bowling: 64,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Dipesh Kandel',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 45,
        bowling: 65,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Tul Bahadur Thapa',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 60,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Natarajan Shah',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 56,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Pratik Shrestha',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 55,
        bowling: 56,
        bowlingType: 'Right arm offbreak',
      },
      {
        name: 'Ricardo Vasconcelos',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 61,
        bowling: 15,
      },
    ],
  },
  {
    name: 'Bolts',
    logo: 'bolts.png',
    themeColor: '#da327c',
    players: [
      {
        name: 'Lahiru Milantha',
        role: 'WK',
        orderType: 'TOP',
        isCaptain: false,
        batting: 80,
        bowling: 0,
      },
      {
        name: 'Aasif Sheikh',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 80,
        bowling: 30,
      },
      {
        name: 'Anil Sah',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: true,
        batting: 78,
        bowling: 46,
      },
      {
        name: 'Loftie Eaton',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 75,
        bowling: 70,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Sanjay Krishnamurthi',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 64,
        bowling: 60,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Mayan Yadav',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 65,
        bowling: 34,
      },
      {
        name: 'Rupesh SIngh',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 63,
        bowling: 65,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Wayne Parnell',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 34,
        bowling: 78,
        bowlingType: 'Left arm fast',
      },
      {
        name: 'Kishor Mahato',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 34,
        bowling: 75,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Tul Bahadur Thapa',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 34,
        bowling: 68,
        bowlingType: 'Left arm spin',
      },
      {
        name: 'Lalit Rajbanshi',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 18,
        bowling: 82,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Aaditya Mahata',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 54,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Shubh Kansakar',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 62,
        bowling: 14,
      },
      {
        name: 'Sachin Bhatt',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 12,
        bowling: 56,
        bowlingType: 'Leg spin',
      },
      {
        name: 'Imran Tahir',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 44,
        bowling: 83,
        bowlingType: 'Leg spin',
      },
    ],
  },
  {
    name: 'Rhinos',
    logo: 'rhino.png',
    themeColor: '#cc682d',
    players: [
      {
        name: 'Deepak Bohara',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 64,
        bowling: 30,
      },
      {
        name: 'Dawid Malan ',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 84,
        bowling: 30,
      },
      {
        name: 'Dev Khanal ',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 73,
        bowling: 40,
      },
      {
        name: 'Ravi Bopara',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 78,
        bowling: 69,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Kushal Malla',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: true,
        batting: 78,
        bowling: 70,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Saif Zaib',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 75,
        bowling: 69,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Arjun Saud',
        role: 'WK',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 64,
        bowling: 0,
      },
      {
        name: 'Sohail Tanvir',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 53,
        bowling: 77,
        bowlingType: 'Left arm medium',
      },
      {
        name: 'Rijan Dhakal',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 32,
        bowling: 70,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Kamal Singh Airee',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 35,
        bowling: 68,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Bipin Acharya',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 15,
        bowling: 63,
        bowlingType: 'Right arm offbreak',
      },
      {
        name: 'Bipin Rawal',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 65,
        bowling: 0,
      },
      {
        name: 'Alpesh Ramjani',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 58,
        bowling: 59,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Ranjit Kumar',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 32,
        bowling: 58,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Amar Rautela',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 61,
        bowling: 15,
      },
    ],
  },
  {
    name: 'Yaks',
    logo: 'yak.png',
    themeColor: '#22ccffff',
    players: [
      {
        name: 'Priyank Panchal',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 74,
        bowling: 30,
      },
      {
        name: 'Max O`Dowd',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 72,
        bowling: 30,
      },
      {
        name: 'Mark Watt',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 70,
        bowling: 20,
      },
      {
        name: 'William Bosisto',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 73,
        bowling: 75,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Pawan Sarraf',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 67,
        bowling: 63,
        bowlingType: 'Slow right arm',
      },
      {
        name: 'Najibullah Zadran',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 66,
        bowling: 20,
      },
      {
        name: 'Arjun Gharti',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 68,
        bowling: 0,
      },
      {
        name: 'Gulshan Kumar Jha',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 79,
        bowling: 73,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Sompal Kami',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: true,
        batting: 51,
        bowling: 83,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Bipin Sharma',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 32,
        bowling: 67,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Nandan Kumar Yadav',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 45,
        bowling: 75,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Deepak Dumre',
        role: 'WK',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 58,
        bowling: 0,
      },
      {
        name: 'Yuvraj Khatri',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 66,
        bowlingType: 'Leg spin',
      },
      {
        name: 'Imran Sheikh',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 60,
        bowling: 23,
      },
      {
        name: 'Unish Singh',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 23,
        bowling: 60,
        bowlingType: 'Right arm medium',
      },
    ],
  },
  {
    name: 'Kings',
    logo: 'kings.png',
    themeColor: '#002a6f',
    players: [
      {
        name: 'Sam Heazlett',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 79,
        bowling: 30,
      },
      {
        name: 'Lokesh Bam',
        role: 'WK',
        orderType: 'TOP',
        isCaptain: false,
        batting: 74,
        bowling: 0,
      },
      {
        name: 'Martin Guptill',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 86,
        bowling: 31,
      },
      {
        name: 'Faf du Plessis',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 93,
        bowling: 40,
      },
      {
        name: 'Basir Ahamad',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 77,
        bowling: 20,
      },
      {
        name: 'Naren Bhatta',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 67,
        bowling: 64,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Shubham Ranjane',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 67,
        bowling: 64,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Pratish GC',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 66,
        bowling: 73,
        bowlingType: 'Left arm medium',
      },
      {
        name: 'Marchant de Lange',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 60,
        bowling: 80,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Sandeep Lamichhane',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: true,
        batting: 50,
        bowling: 88,
        bowlingType: 'Leg Spin',
      },
      {
        name: 'Surya Tamang',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 68,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Narayan Joshi',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 66,
        bowling: 60,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Shankar Rana',
        role: 'BAT',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 57,
        bowling: 29,
      },
      {
        name: 'Dipak Bohara',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 62,
        bowling: 0,
      },
      {
        name: 'Subash Bhandari',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 22,
        bowling: 65,
        bowlingType: 'Right arm offbreak',
      },
    ],
  },
  {
    name: 'Lions',
    logo: 'lion.png',
    themeColor: '#f20d0dff',
    players: [
      {
        name: 'Sumit Maharjan',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 62,
        bowling: 15,
      },
      {
        name: 'D’Arcy Short',
        role: 'AR',
        orderType: 'TOP',
        isCaptain: false,
        batting: 72,
        bowling: 57,
        bowlingType: 'Left-Arm Spinner',
      },
      {
        name: 'Rohit Paudel',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: true,
        batting: 85,
        bowling: 50,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Niroshan Dickwella',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 65,
        bowling: 0,
      },
      {
        name: 'Sundeep Jora',
        role: 'BAT',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 75,
        bowling: 20,
      },
      {
        name: 'JJ Smit',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 65,
        bowling: 68,
        bowlingType: 'Left arm medium',
      },
      {
        name: 'Dilip Nath',
        role: 'WK',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 63,
        bowling: 0,
      },
      {
        name: 'Sher Malla',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 69,
        bowling: 80,
        bowlingType: 'Sloq right arm',
      },
      {
        name: 'Trumpelmann',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 31,
        bowling: 69,
        bowlingType: 'Left arm fast',
      },
      {
        name: 'Tilak Bhandari',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 35,
        bowling: 64,
        bowlingType: 'Leg spinner',
      },
      {
        name: 'Dipesh Kandel',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 45,
        bowling: 65,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Abhishesh Gautam',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 61,
        bowlingType: 'Slow left arm',
      },
      {
        name: 'Gulbadin Naib',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 73,
        bowling: 76,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Aadil Khan',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 52,
        bowling: 0,
      },
      {
        name: 'Dinesh Adhikari',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 24,
        bowling: 54,
        bowlingType: 'Right arm medium',
      },
    ],
  },
  {
    name: 'Avengers',
    logo: 'avenger.png',
    themeColor: '#4f0021',
    players: [
      {
        name: 'Kushal Bhurtel',
        role: 'AR',
        orderType: 'TOP',
        isCaptain: true,
        batting: 86,
        bowling: 73,
        bowlingType: 'Slow right arm',
      },
      {
        name: 'Adam Rossington',
        role: 'WK',
        orderType: 'TOP',
        isCaptain: false,
        batting: 80,
        bowling: 0,
      },
      {
        name: 'Jason Roy',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 90,
        bowling: 30,
      },
      {
        name: 'James Neesham',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 86,
        bowling: 80,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Trit Raj Das',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 64,
        bowling: 53,
        bowlingType: 'Right arm medium',
      },
      {
        name: 'Arjun Kumal',
        role: 'WK',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 66,
        bowling: 0,
      },
      {
        name: 'Kiran Thagunna',
        role: 'AR',
        orderType: 'MIDDLE',
        isCaptain: false,
        batting: 65,
        bowling: 65,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Sandeep Khatri',
        role: 'BAT',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 61,
        bowling: 13,
      },
      {
        name: 'Daniel Dougthwaite',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 57,
        bowling: 70,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Akash Chand',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 30,
        bowling: 69,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Sagar Dhakal',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 32,
        bowling: 73,
        bowlingType: 'Left arm spin',
      },
      {
        name: 'Dinesh Kharel',
        role: 'BAT',
        orderType: 'TOP',
        isCaptain: false,
        batting: 63,
        bowling: 21,
      },
      {
        name: 'Matt Taylor',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 25,
        bowling: 64,
        bowlingType: 'Left arm medium',
      },
      {
        name: 'Abhishek Tiwari',
        role: 'AR',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 53,
        bowling: 56,
        bowlingType: 'Right arm fast',
      },
      {
        name: 'Bipin Khatri',
        role: 'BOWL',
        orderType: 'LOWER',
        isCaptain: false,
        batting: 31,
        bowling: 59,
        bowlingType: 'Slow left arm',
      },
    ],
  },
];
